### ISSUE TITLE
Remarks on documentation for cpu_affinity

### ISSUE THREAD

**Issue by awischnewski** [ros-realtime/ros2-realtime-examples#7]
I have been going through some of the examples now and wanted to share the points which I think could be helpful for new users. I'll put this feedback on a per package basis and will start working on a pull request with some suggestions to implement it. If you have any comments on the points below or if I missed something, please let me know.

- [ ] Add a section for configuring which CPUs are being used by the OS in the bootloader (https://www.skenz.it/cs/kernel_boot_parameters for grub) to prevent other things to get scheduled on that core. 
- [ ] Add a note on adding the CPU core to *htop*, at least mention that its required. 
- [ ] Add a note that pthread counts from 0, while htop starts from 1. (If we pin to 1, its going to appear as 2). 
- [ ] The `rclcpp::init` call seems to create one more subthread in the middleware examlpe (even though the middleware threads are created on node construction) which is not assigned to the correct cpu. I would move it behind the configuration, as this seems to be the intent of the example "assign everything the same cpu affinity". 
- [ ] Add some general documentation to the readme, similar to the *minimal_scheduling* example

**Comment by awischnewski** [comment]
Moving the still valid points to the corresponding pull request #4 .

**Comment by LanderU** [comment]
> Add a note that pthread counts from 0, while htop starts from 1. (If we pin to 1, its going to appear as 2).

Note that you can configure your htop config to start the CPU number from 0 instead of 1.

![image](https://user-images.githubusercontent.com/11192915/167464558-8c811e71-7d79-40f3-aa0e-f5f6eba8b2a1.png)

cc @carlossvg
